In [1]:
import tensorflow as tf

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 42s 4us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.04332744,  0.07529439,  0.39424974,  0.27937672, -0.1396278 ,
        -0.01116064, -0.65797937,  0.2784049 , -0.17318168, -0.25066572]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.1019324 , 0.10524351, 0.14478244, 0.12907055, 0.08488986,
        0.09652691, 0.05055203, 0.12894517, 0.08208873, 0.07596835]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3379333

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0663 - accuracy: 0.9787
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0589 - accuracy: 0.9812
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0536 - accuracy: 0.9823
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0485 - accuracy: 0.9839
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0443 - accuracy: 0.9853
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0405 - accuracy: 0.9869
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0398 - accuracy: 0.9870
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0352 - accuracy: 0.9882
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0328 - accuracy: 0.9886
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.032

In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0851 - accuracy: 0.9792


[0.0851236954331398, 0.979200005531311]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.54739297e-08, 2.87856627e-10, 2.19132698e-06, 5.84182853e-04,
        5.73281114e-13, 4.39692691e-08, 6.74485030e-16, 9.99413371e-01,
        1.12369023e-07, 1.83152906e-07],
       [2.58312260e-11, 1.15396411e-04, 9.99879241e-01, 5.14663952e-06,
        6.96102661e-17, 7.39081187e-08, 8.31843128e-09, 1.05969834e-12,
        8.62173692e-08, 8.44681372e-17],
       [9.23737389e-08, 9.98676002e-01, 6.24000750e-05, 1.32188225e-05,
        8.52965968e-06, 4.49325944e-06, 1.92874595e-05, 9.08257789e-04,
        3.07416456e-04, 1.73216947e-07],
       [9.99974608e-01, 1.13299717e-10, 2.55880673e-06, 1.28764670e-08,
        7.97179123e-09, 7.38460187e-07, 6.79837331e-06, 1.30329936e-05,
        8.38357650e-09, 2.25293138e-06],
       [3.68728280e-07, 5.99727698e-11, 3.37322922e-06, 6.94686619e-09,
        9.97281790e-01, 3.78632620e-07, 1.91699246e-06, 1.67108756e-05,
        4.00951983e-08, 2.69548059e-03]], dtype=float32)>